/**
 * Item icon cells on Showdown's item icon sheet, one per item in
 * `data/items.ts`. **Generated by `scripts/gen-item-icons.ts`; do not edit.**
 * `test/item-icons.test.ts` regenerates it and fails if this file differs.
 *
 * Lives under `ui/` because it is presentation: which cell of a sprite sheet
 * draws an item says nothing about what the item does, and `data/` is what
 * `contentHash` will be computed over.
 */
export const ITEM_ICONS: Readonly<Record<string, number>> = {
  leftovers: 242,
  lifeorb: 249,
  focussash: 151,
  assaultvest: 581,
  rockyhelmet: 417,
  expertbelt: 132,
  shellbell: 438,
  eviolite: 130,
  punchingglove: 749,
  weaknesspolicy: 609,
  choiceband: 68,
  choicespecs: 70,
  choicescarf: 69,
  muscleband: 297,
  wiseglasses: 539,
  silkscarf: 444,
  charcoal: 61,
  mysticwater: 300,
  miracleseed: 292,
  magnet: 273,
  blackbelt: 32,
  twistedspoon: 520,
  sharpbeak: 436,
  oranberry: 319,
  sitrusberry: 448,
  lumberry: 262,
  chestoberry: 65,
  persimberry: 334,
  leppaberry: 244,
  occaberry: 311,
  passhoberry: 329,
  rindoberry: 409,
  wacanberry: 526,
  chopleberry: 71,
  payapaberry: 330,
  yacheberry: 567,
  habanberry: 185,
  colburberry: 78,
};
