/**
 * Every word the card battle sandbox shows a player, in one table. The
 * sandbox is outside the design bible (`docs/spec/gymrun-card-battle-engine-rulings.md`),
 * so these are working words for a fun test, kept in data so a playtest can
 * reword them without touching the screen.
 */
import type { DamageKeyword } from '../core/cards/defs';
import type { PlayBlock } from '../core/cards/state';

export const CARD_COPY = {
  title: 'Card battle test',
  round: 'Round',
  draw: 'Draw',
  discard: 'Discard',
  endTurn: 'End Turn',
  undo: 'Undo',
  cancel: 'Cancel',
  inspect: 'Inspect',
  menu: 'Menu',
  close: 'Close',
  exit: 'Exit',
  restart: 'Restart',
  newSeed: 'New seed',
  copyLog: 'Copy log',
  copied: 'Log copied',
  copyFailed: 'Select the log below and copy it',
  seed: 'Seed',
  won: 'Won',
  lost: 'Lost',
  pickUnit: 'Pick who plays it',
  pickTarget: 'Pick a target',
  pickAlly: 'Pick an ally',
  pickTile: 'Pick a tile',
  inspectHint: 'Tap a card to inspect it',
  once: 'Once',
  neutral: 'Neutral',
  cost: 'MP',
  hp: 'HP',
  shield: 'Shield',
  shieldShort: 'Sh',
  baseShield: 'Base',
  slots: 'Slots',
  intentNone: 'Wait',
  reasons: {
    noMp: 'Not enough MP',
    noSlot: 'No free slot',
    wrongZone: 'Danger zone only',
    noTarget: 'Nothing to hit',
    fainted: 'Fainted',
  } satisfies Record<PlayBlock, string>,
  keyword: {
    strike: 'Strike',
    pierce: 'Pierce',
    slash: 'Slash',
    blast: 'Blast',
    move: 'Move',
    shield: 'Shield',
    target: 'Target',
  } satisfies Record<DamageKeyword | 'move' | 'shield' | 'target', string>,
  effect: {
    shieldSelf: (n: number) => `Shield ${n}, self`,
    shieldFriendly: (n: number) => `Shield ${n}, ally`,
    gainMp: (n: number) => `+${n} MP on use`,
    mpNextTurns: (n: number, turns: number) => `+${n} MP next ${turns} turns`,
    grantMove: (n: number) => `Ally: Move ${n}, no MP`,
    drawNext: (n: number) => `Next hand +${n}, not mine`,
  },
  beats: {
    moved: (who: string) => `${who} moves`,
    damaged: (who: string, n: number) => `${who} takes ${n}`,
    defeated: (who: string) => `${who} defeated`,
    fainted: (who: string) => `${who} fainted`,
    missed: (who: string) => `${who} missed`,
    shielded: (who: string, n: number) => `${who} +${n} shield`,
    fizzled: (card: string) => `${card} fizzled`,
    reshuffled: 'Discard shuffled in',
    roundStarted: (n: number) => `Round ${n}`,
  },
} as const;
