/**
 * Every word the card battle sandbox shows a player, in one table. The
 * sandbox is outside the design bible (`docs/spec/gymrun-card-battle-engine-rulings.md`),
 * so these are working words for a fun test, kept in data so a playtest can
 * reword them without touching the screen.
 */
import type { DamageKeyword } from '../core/cards/defs';
import type { PlayBlock } from '../core/cards/state';

export const CARD_COPY = {
  title: 'Card battle test',
  round: 'Round',
  draw: 'Draw',
  discard: 'Discard',
  endTurn: 'End Turn',
  start: 'Start',
  deployHint: 'Place your units on the home rows, then Start',
  placeUnit: (unit: string) => `${unit}: pick a home tile`,
  scenario: 'Scenario',
  /** A scenario's grade total, the sum of its enemies' provisional grades. */
  grade: (n: number) => `Grade ${n}`,
  undo: 'Undo',
  cancel: 'Cancel',
  inspect: 'Inspect',
  menu: 'Menu',
  close: 'Close',
  exit: 'Exit',
  restart: 'Restart',
  newSeed: 'New seed',
  copyLog: 'Copy log',
  copied: 'Log copied',
  copyFailed: 'Select the log below and copy it',
  seed: 'Seed',
  won: 'Won',
  lost: 'Lost',
  pickUnit: 'Pick who plays it',
  cannotPlay: (units: string, reason: string) => `${units}: ${reason}`,
  pickTarget: 'Pick a target',
  pickAlly: 'Pick an ally',
  pickTile: 'Pick a tile',
  pickTileBlock: 'Pick a tile · a shield blocks a Strike',
  pickTileAllies: 'Pick a tile · a marked tile hits an ally too',
  pickTargetAllies: 'Pick a target · a marked one hits an ally too',
  inspectHint: 'Tap a card or an enemy to inspect it',
  /** Round 1 under opening grace (A1, A7): the note line, while nothing else is said. */
  graceBoard: 'Round 1: enemies are getting into position',
  /** Inspect entries for the rules of the grace and friendly fire patch (A7). */
  rule: {
    grace: 'Round 1: most enemies set up instead of attacking.',
    fast: 'Fast: attacks from round 1, for 1.',
    blastAllies: 'Blast hits allies on its tiles too. Not the unit that plays it.',
    blastAlliesCaster: 'Blast hits allies on its tiles too, the unit that plays it included.',
  },
  enemyStats: (hp: number, base: number) => `HP ${hp} · Base ${base}`,
  /** The unit filter (A6): tap a unit to see only what it can play. */
  filterShowing: (unit: string) => `Showing ${unit}`,
  filterShowAll: 'Show all',
  filterOther: (n: number) => `+${n} other`,
  once: 'Once',
  neutral: 'Neutral',
  cost: 'MP',
  hp: 'HP',
  shield: 'Shield',
  shieldShort: 'Sh',
  baseShield: 'Base',
  slots: 'Slots',
  intentNone: 'Wait',
  /** The Fast badge on an enemy's token and panel. */
  fast: 'Fast',
  reasons: {
    noMp: 'Not enough MP',
    noSlot: 'No free slot',
    wrongZone: 'Danger zone only',
    noTarget: 'Nothing to hit',
    fainted: 'Fainted',
  } satisfies Record<PlayBlock, string>,
  keyword: {
    strike: 'Strike',
    pierce: 'Pierce',
    slash: 'Slash',
    blast: 'Blast',
    move: 'Move',
    shield: 'Shield',
    target: 'Target',
  } satisfies Record<DamageKeyword | 'move' | 'shield' | 'target', string>,
  effect: {
    shieldSelf: (n: number) => `Shield ${n}, self`,
    shieldFriendly: (n: number) => `Shield ${n}, ally`,
    gainMp: (n: number) => `+${n} MP on use`,
    mpNextTurns: (n: number, turns: number) => `+${n} MP next ${turns} turns`,
    grantMove: (n: number) => `Ally: Move ${n}, no MP`,
    drawNext: (n: number) => `Next hand +${n}, not mine`,
  },
  roundLog: 'Round log',
  replayRound: 'Replay round',
  back: 'Back',
  logEmpty: 'No round played yet',
  /** The round playback and the round log: one line per thing that happened, in order. */
  log: {
    plays: (who: string, card: string) => `${who} · ${card}`,
    acts: (who: string, act: string) => `${who} · ${act}`,
    moves: (who: string, way: string) => `${who} moves ${way}`,
    waits: (who: string) => `${who} waits`,
    way: { up: 'up', down: 'down', left: 'left', right: 'right' },
    converted: 'Strike becomes Pierce',
    fizzledGone: 'Fizzled: target gone',
    fizzledNothing: 'Fizzled: nothing to hit',
    friendlyFire: (who: string) => `${who}: friendly fire`,
    notPlayed: 'Not played: fainted',
    hit: (who: string, n: number) => `${who} hit for ${n}`,
    absorbed: { shield: (n: number) => `shield -${n}`, baseShield: (n: number) => `base -${n}`, hp: (n: number) => `HP -${n}` },
    missed: 'Missed: nobody on the lit tiles',
    shielded: (who: string, n: number) => `${who} shield +${n}`,
    shieldDrops: (who: string, n: number) => `${who} shield ${n} wears off`,
    defeated: (who: string) => `${who} defeated`,
    fainted: (who: string) => `${who} fainted`,
    mp: (who: string, n: number) => `${who} +${n} MP`,
    roundMp: (who: string) => `MP +1: ${who}`,
    drawQueued: (n: number) => `Next hand +${n}`,
    next: 'Next round',
    telegraph: (who: string, act: string) => `${who}: ${act}`,
    reshuffled: 'Discard shuffled in',
    round: (n: number) => `Round ${n}`,
    step: (n: number, of: number) => `${n}/${of}`,
  },
} as const;
