/**
 * Acquiring Pokemon: two routes, one code path.
 *
 * A run can gain a party member from a reward card (`species`, which Stage 3
 * typed and gated off) or from a wild node that offers the Pokemon it just
 * defeated. Those are two *sources* and one *decision*, and this file is the
 * decision: an offer, the three answers a player can give it, and the rule that
 * neither answer can leave the party over `PARTY_SIZE`.
 *
 * ## Why the species reward was gated, and why it is on now
 *
 * At `PARTY_SIZE` 1 a species reward was not an addition, it was a forced swap
 * of the run's only Pokemon — either the most interesting decision in the game
 * or an instant run-ender, with no way to know which without playing it. Stage
 * 3 wrote the type, wrote the pool entries, and left
 * `tuning.allowSpeciesRewards` false with a note saying to revisit it when a
 * swap cost a slot instead of the whole run. That is now, so it is on.
 *
 * ## The one rule
 *
 * **Declining is always legal, and releasing is permanent.** There is no box
 * and no reserve. A box needs a screen, a capacity rule, and an answer to what
 * happens to it on a wipe, and none of those are interesting decisions — what
 * is interesting is being handed something good when you are full and having to
 * decide what it is worth. Making the release permanent is what gives that
 * question teeth.
 *
 * ## Determinism
 *
 * Every offer is drawn at **map generation**, from the `rewards` stream, in
 * node index order — the same rule as every other offer in the game and for the
 * same reason. Whether an encounter offers its species must not depend on how
 * the battle went, only on whether the player won, or the number of draws
 * consumed before the next node would become a function of play.
 */
import { describeSpecCard } from './battle/driver';
import { createPartyMember } from './party';
import type { RngStream } from './rng';
import type { ItemId, PokemonSpec, PokemonState } from './types';
import { PARTY_SIZE, PARTY_TUNING } from '../data/partyTuning';
import { encounterAcquisitionRate } from '../data/rewardPools';
import { playerLevel } from '../data/scaling';
import type { Tuning } from '../data/tuning';
import type { Tier } from './types';

/** Where an offer came from. Display and metrics only; the decision is the same. */
export type AcquisitionSource = 'reward' | 'encounter';

/**
 * A Pokemon on the table, and what taking it would cost.
 *
 * The `spec` is fully resolved by the time an offer exists — level, ability and
 * moveset are all decided at map generation. That is what lets the run log
 * store a *decision* rather than a Pokemon: replaying the seed reconstructs the
 * offer, and a log naming the species would keep replaying happily after a pool
 * edit and hand the player a member their run never met.
 */
export interface AcquisitionOffer {
  /** The node that offers it, so a screen or a test can tie the two together. */
  nodeId: string;
  source: AcquisitionSource;
  spec: PokemonSpec;
}

/**
 * What the player did about an offer.
 *
 * Three answers, and `release` carries the slot because that is the part the
 * player chose. Stored in the run log verbatim: unlike a reward, this is not an
 * index into a generated list that replay can reconstruct — it is the input
 * itself, and there is nothing derived in it.
 */
export type AcquisitionDecision =
  | { kind: 'decline' }
  /** Take it into a free slot. Illegal at a full party. */
  | { kind: 'accept' }
  /** Take it and release the member in this slot. Illegal at anything else. */
  | { kind: 'release'; slot: number };

/** Whether the party has room without releasing anything. */
export function hasRoom(party: readonly PokemonState[]): boolean {
  return party.length < PARTY_SIZE;
}

/**
 * The level an acquired member arrives at.
 *
 * Below the segment's curve by `joinLevelOffset`, which is the cost of a free
 * Pokemon: at zero, taking one would be strictly better than declining and
 * there would be no decision in it. Floored at 1, and the party levels it to
 * the curve at the next gym like everything else — so the penalty is paid for
 * the remainder of the current segment and no longer.
 */
export function joinLevelFor(segment: number): number {
  return Math.max(1, playerLevel(segment) - PARTY_TUNING.joinLevelOffset);
}

/**
 * The offer a wild node makes, or null when it makes none.
 *
 * **The species is the one that was just defeated, re-levelled — not a fresh
 * roll.** That is what "no new species generation path" means concretely: the
 * team was generated by `generateWildTeam` in pass 2 from the `randomizer`
 * stream, and this reads it back rather than drawing again. A second generation
 * path would be a second set of rules for what a wild Pokemon is, and the first
 * divergence between them would be invisible.
 *
 * Exactly one draw from the `rewards` stream, always, whether or not the offer
 * appears. A rate check that only rolled when it might succeed would make the
 * *number* of draws depend on the node's tier, and every seed's later reward
 * rolls would shift when the tier table moved.
 */
export function generateEncounterAcquisition(
  nodeId: string,
  lead: PokemonSpec,
  tier: Tier,
  segment: number,
  stream: RngStream,
  tuning: Tuning,
): AcquisitionOffer | null {
  // Drawn *before* the flag is read, and deliberately. A flag that skipped the
  // draw would shift every later reward roll in the seed, and the two
  // configurations it exists to compare would stop being comparable.
  const roll = stream.nextFloat();
  if (!tuning.allowEncounterAcquisitions) return null;
  if (roll >= encounterAcquisitionRate(tier)) return null;
  return {
    nodeId,
    source: 'encounter',
    spec: { ...lead, moves: [...lead.moves], level: joinLevelFor(segment) },
  };
}

/**
 * Whether a decision is one the party could actually take.
 *
 * Returns the reason it could not, or null. Checked before applying rather than
 * clamped afterwards: a decision that silently becomes a different decision is
 * a log that replays into a different run, which is the failure the whole
 * decision-log design exists to prevent.
 */
export function decisionRefusal(
  party: readonly PokemonState[],
  decision: AcquisitionDecision,
): string | null {
  if (decision.kind === 'decline') return null;
  if (decision.kind === 'accept') {
    return hasRoom(party) ? null : `party is full (${party.length}/${PARTY_SIZE})`;
  }
  if (hasRoom(party)) return 'party has room, so nothing needs releasing';
  if (!party[decision.slot]) return `no party member in slot ${decision.slot}`;
  return null;
}

/**
 * Apply a decision. **The only path by which a party gains or loses a member.**
 *
 * Returns a new party, like every other party transition. The released member
 * is dropped rather than moved anywhere, which is the permanence the design
 * asked for; the acquired one is appended rather than inserted into the freed
 * slot, so `release` is a release and not a swap-in-place — the player reorders
 * the party on the party screen if the lead matters to them, and hiding a
 * reorder inside an acquisition would be a second decision in one act.
 */
export function applyAcquisition(
  party: readonly PokemonState[],
  offer: AcquisitionOffer,
  decision: AcquisitionDecision,
): { party: PokemonState[]; freed: ItemId | null } {
  const refusal = decisionRefusal(party, decision);
  if (refusal) throw new RangeError(`Cannot apply acquisition decision: ${refusal}`);

  if (decision.kind === 'decline') return { party: [...party], freed: null };
  const joined = createPartyMember(offer.spec);
  if (decision.kind === 'accept') return { party: [...party, joined], freed: null };

  /*
   * A released member hands their item back rather than taking it with them.
   *
   * The release itself is still permanent — there is no box and no retrieval,
   * and that is what gives the choice teeth. What changed in Stage 4.5.1 is
   * that the *item* is not part of the price: an item is destroyed only by an
   * explicit discard, and letting a Pokemon go is not one.
   */
  return {
    party: [...party.filter((_, index) => index !== decision.slot), joined],
    freed: party[decision.slot]?.item ?? null,
  };
}

/**
 * A one-line label for an offer. Shared by the acquisition screen and the report.
 *
 * Asks the adapter for the species' real name and types rather than echoing the
 * spec, for the same reason `describeReward` resolves an item id: the spec
 * carries what was rolled and the screen shows what the player will see on the
 * field.
 */
export function describeOffer(offer: AcquisitionOffer): string {
  const card = describeSpecCard(offer.spec);
  return `${card.species} (Lv${card.level}, ${card.types.join('/')})`;
}
