/**
 * The item icon index, generated: every item in `data/items.ts` mapped to its
 * cell on Showdown's item icon sheet, as `@pkmn/img` numbers it.
 *
 *   npx vite-node scripts/gen-item-icons.ts
 *
 * `@pkmn/img`'s default export bundles its whole sprite index (every species,
 * every item, every avatar) behind `Icons.getItem`, which cost the shipped
 * bundle 43 kB gzipped for thirty-eight lookups. Its `adaptable` entry takes
 * the data from the caller instead, so this writes the thirty-eight numbers
 * GYMRUN needs into `src/ui/theme/itemIcons.ts` and `ui/slots.ts` hands them
 * to that entry. `test/item-icons.test.ts` regenerates the table against the
 * package and fails if the file on disk differs, so the numbers cannot drift.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { Icons } from '@pkmn/img';

import { ITEMS } from '../src/data/items';

export const TARGET = join(process.cwd(), 'src/ui/theme/itemIcons.ts');

/** The cell number, recovered from the offsets the full package computes. */
export function spriteNumber(name: string): number | null {
  const icon = Icons.getItem(name);
  if (!icon || icon.url.length === 0) return null;
  const column = Math.round(-icon.left / 24);
  const row = Math.round(-icon.top / 24);
  return row * 16 + column;
}

export function renderTable(): string {
  const rows = ITEMS.map((item) => {
    const number = spriteNumber(item.name);
    if (number === null) throw new Error(`No icon for ${item.name}`);
    return `  ${item.id}: ${number},`;
  });
  return `/**
 * Item icon cells on Showdown's item icon sheet, one per item in
 * \`data/items.ts\`. **Generated by \`scripts/gen-item-icons.ts\`; do not edit.**
 * \`test/item-icons.test.ts\` regenerates it and fails if this file differs.
 *
 * Lives under \`ui/\` because it is presentation: which cell of a sprite sheet
 * draws an item says nothing about what the item does, and \`data/\` is what
 * \`contentHash\` will be computed over.
 */
export const ITEM_ICONS: Readonly<Record<string, number>> = {
${rows.join('\n')}
};
`;
}

if (process.argv.includes('--write')) {
  writeFileSync(TARGET, renderTable());
  console.log(`wrote ${TARGET} (${ITEMS.length} items)`);
}
