/**
 * The encounter library's record shape. **Stage 6.0.**
 *
 * An encounter is one trainer battle as a game shipped it: who the trainer is,
 * where the fight is, the party at its canonical levels, and the moves and
 * items where the game set them. Every field is a fact about the source, cited
 * per record. Nothing here is tuned; the fit to a GYMRUN segment (level shift,
 * trim to size, pool projection) happens in `index.ts` and `core/`, never in
 * these rows.
 *
 * The per-game files are GENERATED by `scripts/import-encounters/` from the
 * pret decompilations (Gen 1 to 4) and hand-curated for later games. The
 * header of each file says which.
 */
import type { Gender, TypeName } from '../../core/types';

/** The games the library cites. Each is a slug the record id starts with. */
export type GameId =
  | 'rby'
  | 'yellow'
  | 'gs'
  | 'crystal'
  | 'rs'
  | 'emerald'
  | 'frlg'
  | 'platinum'
  | 'hgss'
  | 'bw'
  | 'b2w2'
  | 'xy'
  | 'oras'
  | 'sm'
  | 'usum'
  | 'lgpe'
  | 'swsh'
  | 'bdsp'
  | 'sv';

/** What kind of fight this was in its game. */
export type TrainerRole = 'gym' | 'elite' | 'champion' | 'rival' | 'boss' | 'route';

export interface PartyMember {
  /** Showdown species id, as `data/speciesPools.ts` keys it. */
  species: string;
  level: number;
  /** Showdown move ids, only where the source sets them. Fewer than four means the rest were level-up defaults. */
  moves?: readonly string[];
  /** Showdown item id, only where the source sets one the dex still has. */
  item?: string;
  gender?: Gender;
}

export interface EncounterRecord {
  /** `<game>/<trainer>-<n>`, unique across the library. */
  id: string;
  game: GameId;
  gen: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
  trainer: {
    /** The name the game shows. A rival placeholder is normalised to the canonical name. */
    name: string;
    /** The trainer class as the game shows it. */
    class: string;
    /** A Showdown trainer sprite id under `sprites/trainers/`, checked against the CDN listing, or null. */
    sprite: string | null;
  };
  role: TrainerRole;
  /** Where the fight is, as precisely as the source says. A region name when it says nothing more. */
  place: string;
  /** The gym's type, for role `gym` only. Absent for a gym with no single type. */
  gymType?: TypeName;
  /** Canonical order. The last member is the ace. */
  party: readonly PartyMember[];
  /** True when the game fought this as a double battle. A fact, not a filter. */
  double?: boolean;
  /**
   * The label this row was read from inside its game's source: a data label
   * (`BrockData`), a trainer constant (`TRAINER_ROXANNE_1`), a file name
   * (`leader_roark.json`), an array index (`trainers[12]`), or for a curated
   * game a page URL. The repository, path and revision are the game file's
   * `EncounterSource`, once per file rather than once per row.
   */
  cite: string;
}

/** Where one game's table was read from. The revision is pinned, so the citation is exact. */
export interface EncounterSource {
  /** `pret/pokered`, or for a curated game the site the rows cite. */
  repo: string;
  /** The commit the files were read at, or the date the pages were read. */
  sha: string;
  /** The files inside the repository that the rows cite, repository-relative. */
  files: readonly string[];
}
