/**
 * The eight gym leaders.
 *
 * A gym is a leader identity, a type, and the segment it guards. Stage 1
 * carried a hardcoded roster alongside those and predicted it would not survive
 * contact with the randomizer; it did not, and it is gone. What is left is the
 * part that was always the real definition: **the type is the gym**. Everything
 * else — which Pokemon, at what level, how many — is generated by
 * `generateGymTeam` from this type plus the segment's row in data/scaling.ts.
 *
 * That is why this file has no levels and no team sizes in it. Levels come from
 * the curve; team sizes come from `opponentTeamSize`, which is a function of
 * PARTY_SIZE so that Stage 4 raising the party does not turn the back half of
 * the run into a formality. A leader who genuinely needs to break that curve
 * has `teamSize` below, and using it should feel like a decision.
 */

export interface GymDefinition {
  id: string;
  leader: string;
  /**
   * The gym's type identity.
   *
   * Every member of a generated gym team has this type. Not "mostly" — the
   * property is asserted across many seeds in test/randomizer.test.ts, because
   * a Rock gym that occasionally fields a Gyarados is a gym whose identity the
   * player cannot plan against, and planning against it is the whole reason a
   * gym is announced before you fight it.
   */
  type: string;
  /** Which segment this gym caps. */
  segment: number;
  /** One line of flavour, shown on the map and the summary. */
  blurb: string;
  /**
   * Species ids this leader draws from, in place of "every species of the type".
   *
   * Unset for all eight today. It exists because "type identity" and "the
   * roster I want" are different constraints, and the day a leader needs the
   * second one it should not require a code change.
   */
  allow?: readonly string[];
  /** Species ids this leader never draws, on top of data/blacklists.ts. */
  deny?: readonly string[];
  /**
   * Override the team size the curve would give this gym.
   *
   * Deliberately absent everywhere. A leader that is bigger than its neighbours
   * is a difficulty cliff dressed as flavour, and the whole point of putting
   * sizes in data/scaling.ts is that the simulator can move them as one curve.
   */
  teamSize?: number;
}

export const GYMS: readonly GymDefinition[] = [
  { id: 'gym-rock', leader: 'Garnet', type: 'Rock', segment: 0, blurb: 'Everything she fields is heavier than you.' },
  { id: 'gym-water', leader: 'Marina', type: 'Water', segment: 1, blurb: 'Patient. Expects to outlast you.' },
  { id: 'gym-electric', leader: 'Volta', type: 'Electric', segment: 2, blurb: 'Fast, and does not intend to take a second turn.' },
  { id: 'gym-grass', leader: 'Fern', type: 'Grass', segment: 3, blurb: 'Heals more than you can chip.' },
  { id: 'gym-fire', leader: 'Cinder', type: 'Fire', segment: 4, blurb: 'Trades. Assumes the trade favours her.' },
  { id: 'gym-psychic', leader: 'Solene', type: 'Psychic', segment: 5, blurb: 'Sets up on the turn you spend deciding.' },
  { id: 'gym-ghost', leader: 'Vesper', type: 'Ghost', segment: 6, blurb: 'Half your coverage does nothing here.' },
  { id: 'gym-dragon', leader: 'Draven', type: 'Dragon', segment: 7, blurb: 'The last one. Nothing about it is a formality.' },
];

/** The gym that caps a segment. Throws rather than wrapping: a missing gym is a bug. */
export function gymForSegment(segment: number): GymDefinition {
  const gym = GYMS.find((entry) => entry.segment === segment);
  if (!gym) throw new RangeError(`No gym defined for segment ${segment}`);
  return gym;
}
